services:
  spark-master:
    image: spark:latest
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: spark:latest
    container_name: spark-worker
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
    depends_on:
      - spark-master

  airflow:
    build: .
    container_name: airflow
    restart: always
    depends_on:
      - spark-master
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/airflow/spark_jobs
    ports:
      - "8081:8080"
    command: standalone